### ISSUE TITLE
Connecting to other machines in the cluster from the Windows workstation

### ISSUE THREAD

**Issue by tpetchel** [chef-cft/wombat#109]
Is there some IAM or other magic we can provide that enables you to SSH into other members of the cluster without the need to copy your AWS .pem key to the Windows workstation?

If so, would love to see that added.

**Comment by tpetchel** [comment]
I don't strictly need this, but I'm guessing folks will want to log in directly to the systems to poke around. They could do so from outside the demo environment or copy their .pem key over to the Windows workstation. But if there's a way to make that easier...

**Comment by andrewelizondo** [comment]
Solved by explaining our common key approach
