### ISSUE TITLE
Infranodes aren't available for push jobs

### ISSUE THREAD

**Issue by tpetchel** [chef-cft/wombat#110]
```
C:\Users\Administrator\Desktop> knife job start 'chef-client' --search 'recipe:awesome_customers_delivery'
WARNING: Falling back to Push Jobs v1 mode.
Started.  Job ID: b3cb0230ef11e2ecc2a50222b776dcb7
.Quorum_failed.
command:     chef-client
created_at:  Tue, 21 Jun 2016 18:32:51 GMT
id:          b3cb0230ef11e2ecc2a50222b776dcb7
nodes:
  unavailable: acceptance
run_timeout: 3600
status:      quorum_failed
updated_at:  Tue, 21 Jun 2016 18:32:51 GMT
```

```
C:\Users\Administrator\Desktop> knife node status acceptance
acceptance      unavailable
```

From Chef manage, none of the nodes have an associated IP address. Is that the cause?

**Comment by NickRycar** [comment]
I suspect so -- they likely need to do a CCR first. Does it show up as available if you log in to do a chef client run?

**Comment by tpetchel** [comment]
No, it doesn't. Still getting:

```
C:\Users\Administrator\Desktop> knife node status acceptance
acceptance      unavailable
```

After bootstrapping the instance (doing an initial cc run) from the workstation.

**Comment by tpetchel** [comment]
I haven't confirmed, but I believe this is resolved. When I bootstrapped, it overrode the node's client.rb, which removed the data collector config.

The plan is to do an initial CCR during cloud-init, then you can use push jobs after that.
