### ISSUE TITLE
Extra AMIs are generated

### ISSUE THREAD

**Issue by tpetchel** [chef-cft/wombat#116]
When I run `rake packer:build_amis`, I consistently get two extra AMIs that aren't referenced by the CFN template.

For example:
- `build-node--1466613841`
- `automate-infranode--1466614340`

They're generated before any other systems.

Logs:
https://gist.github.com/tpetchel/440b4fd1c5e31b0ab2c55f2807998226

Perhaps these are used to speed up generation of other systems? No harm having them, but wanted to report in case this is unexpected.

**Comment by andrewelizondo** [comment]
the empty infranode should be fixed by #143
