### ISSUE TITLE
Sorting of infra breaks on an empty array

### ISSUE THREAD

**Issue by NickRycar** [chef-cft/wombat#139]
The new sorting will break if you haven't defined any infranodes.

Propose changing:
  wombat['infranodes'].sort || {}

To:

if wombat['infranodes']
  wombat['infranodes'].sort
else
  {}
end

Testing on a local checkout, and will PR if it works successfully.

**Comment by NickRycar** [comment]
Should be fixed by https://github.com/chef-cft/wombat/pull/140. Closing after merge.

**Comment by andrewelizondo** [comment]
merged!
