### ISSUE TITLE
chef-server::cheffish needs support for environments

### ISSUE THREAD

**Issue by binamov** [chef-cft/wombat#169]
It seems there's an infranodes-info.json one can feed. I imagine it should support this structure:

```
{
    "site-config-acceptance" : {
        "node-in-site-config-acceptance-1" : [ "recipe[push-jobs]", "recipe[site-config]" ],
        "node-in-site-config-acceptance-2" : [ "recipe[push-jobs]", "recipe[some-other-stuff]" ]
        },
    "union" : {
        "node-in-union-1" : [ "recipe[push-jobs]", "recipe[site-config]" ],
        "node-in-union-2" : [ "recipe[push-jobs]", "recipe[some-other-stuff]" ]
        },
    "rehearsal" : {},
    "delivered" : {}
}
```

**Comment by andrewelizondo** [comment]
the way I imagined this, is refactoring the way the infranodes hash works in the wombat.yml, changing the structure from `nodename: runlist` to `nodename: { run_list: runlist, environment: env, etc...}` is the right thing to do to give us some future proofing

**Comment by andrewelizondo** [comment]
https://github.com/chef-cft/wombat/pull/187
