### ISSUE TITLE
Whats in a name?

### ISSUE THREAD

**Issue by cheeseplus** [chef-cft/wombat#180]
As per our own advice, cookbook names should not include such blasphemy as the `-` and shall henceforth use `_` as is the wont of Alvis

**Comment by scarolan** [comment]
Which cookbooks are affected?  Is it just `build-node` and `chef-server`?

**Comment by cheeseplus** [comment]
Yep

**Comment by cheeseplus** [comment]
Actually all the `mock-data` fixture cookbooks too

**Comment by cheeseplus** [comment]
http://img09.deviantart.net/91ce/i/2005/280/0/6/alvis_by_joeadonis.jpg
