### ISSUE TITLE
extend the infranodes hash to `node['recipes']`

### ISSUE THREAD

**Issue by binamov** [chef-cft/wombat#191]
Infra nodes need to have the target cookbook in their _resolved_ runlists aka `node['recipes']` for Automate to consider them to be deploy targets. Extending the hash is probably the most elegant way to solve https://github.com/chef-cft/bjc/issues/68 .

Perhaps this could be done in a way that lets wombat consumers set any number of arbitrary attributes on their infranodes.

**Comment by andrewelizondo** [comment]
chef-cft/bjc#68 doesn't seem to be dependent on this any longer. closing this out as a wontfix
