### ISSUE TITLE
Replace build_demo.sh

### ISSUE THREAD

**Issue by scarolan** [chef-cft/wombat#233]
It's nice to be able to see who each stack belongs to in the GUI.  Perhaps a username or demo name could be prepended to the stack name, like we do with the CAD demo?  Otherwise in BJC they all end up being called `bjc-demo` if you use the defaults.

**Comment by cheeseplus** [comment]
Do you want the name as a tag or does it have to be in the name of the instance? 

Having customer-date seems like it should be unique enough and then you can look at tags.

**Comment by scarolan** [comment]
The things the SAs care about are:
- See the name of the thing in the GUI so I can know who it's for
- Spin up demos from the command line
- Set custom TTL without editing JSON
- Specify whose ssh key to use to spin up the stack (or default to some ENV var)
- Specify a region

The rest of the X-Dept and stuff can be an array of tags perhaps?  Not sure how we should handle that part, if we want to stay compliant with company standards for tagging.

**Comment by scarolan** [comment]
Oh, also, we want to see the version number in the description field for cloudformation stacks.

**Comment by scarolan** [comment]
build_demo.sh is not going away.  closing this.
