### ISSUE TITLE
./wombat deploy bjc-demo fails if there are no logs in packer/logs

### ISSUE THREAD

**Issue by scarolan** [chef-cft/wombat#234]
The deploy command runs in two steps:
1.  Render JSON file based on packer/logs contents (AMI IDs)
2.  Deploy stack from the *.json template

A couple issues that could arise here:
- Brand new user clones BJC repo and attempts the deploy command.  Because he or she has no logs the command fails.  
- User builds brand new AMIs.  Now deploy works, but they are using a one-off version of their own creation that does not match what was committed to github.

I think we might want to consider de-coupling the build and deploy commands.  It will be easier to understand and manage.

**Comment by binamov** [comment]
this should be fixed with the latest wombat in bjc
