### ISSUE TITLE
wombat.yml shouldn't be a hardcoded name

### ISSUE THREAD

**Issue by andrewelizondo** [chef-cft/wombat#265]
for doing multiple pipeline builds in the same repo we should change the hard coded naming of the `wombat.yml` in `lib/wombat/common.rb`

* create an environment variable switch `WOMBAT_YML` similar to the test-kitchen pattern.
* create a cli switch for providing a different `wombat.yml`
* ensure it always defaults to `wombat.yml`

**Comment by cheeseplus** [comment]
Fixed by #266
