### ISSUE TITLE
can't build infranodes

### ISSUE THREAD

**Issue by binamov** [chef-cft/wombat#299]
```
wombat build infranodes
==> Generating certs (if necessary)
An x509 certificate already exists for automate
An x509 certificate already exists for chef
An x509 certificate already exists for compliance
==> Generating SSH keypair (if necessary)
An SSH keypair already exists
==> Starting build for templates: ["infranodes"]
==> $AWS_REGION not set, setting to us-east-1
==> Vendoring cookbooks for infranodes
>>> undefined local variable or method `options' for #<Wombat::BuildRunner:0x30d9500>
```
something with https://github.com/chef-cft/wombat/blob/master/lib/wombat/build.rb

**Comment by scarolan** [comment]
This is blocking BJC changes.  Let's get some more eyeballs on it.

**Comment by binamov** [comment]
interestingly enough, they build on azure. @russellseymour can you take a look, seems we may have introduced a regression into latest wombat?

**Comment by russellseymour** [comment]
I _think_ I have fixed this, although I am not sure that I messed about with the method in question, certainly not the parameters that it is passed.

I have created a PR (#300) for this, please check.
