### ISSUE TITLE
resource group deletions

### ISSUE THREAD

**Issue by binamov** [chef-cft/wombat#323]
related to #322 

`wombat delete -c azure <json-name>`
should be able to delete the resource group produced by
`wombat deploy -c azure <json-name>`

**Comment by russellseymour** [comment]
Unless we track the resource group that has been created by each operation, this is will not be something that can be done automatically.  To get around this, this is what I have done.

The `outputs` sub command will now output all of the workstation public IP address in all resource groups that begin with the project name.  This can be used to selectively delete the correct group.

![image](https://cloud.githubusercontent.com/assets/791658/24297215/d8a9d43e-1099-11e7-9b75-fd1098744d3a.png)

If an attempt to delete the parent group, the one named after the project name, is made a warning will be displayed about this state.

![image](https://cloud.githubusercontent.com/assets/791658/24297260/0a61f89e-109a-11e7-8018-d766da7bc4f3.png)

If it _must_ be deleted then the `--force` flag should be set.

/cc @binamov
